language: node_js

node_js:
  - 14

branches:
  only:
    - master

cache:
  npm: false

script:
  npm run lint && npm test && npm run build

after_success:
  npm install surge && surge ./dist $DOMAIN
